package model

const val TEAM_MISMATCH = "TEAM_MISMATCH"
const val LICENSE_IS_NOT_AVAILABLE_TO_ASSIGN = "LICENSE_IS_NOT_AVAILABLE_TO_ASSIGN"
const val INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
const val LICENSE_NOT_FOUND = "LICENSE_NOT_FOUND"
const val INVALID_CONTACT_EMAIL = "INVALID_CONTACT_EMAIL"
const val TEAM_NOT_FOUND = "TEAM_NOT_FOUND"
const val PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"

